"use client";
/* eslint-disable @next/next/no-html-link-for-pages */

import { useCallback, useEffect, useState, type ReactNode } from "react";
import { fallbackBackground, fallbackCommittee, fallbackProposalPoints, fallbackSurvey, type CommitteeMember, type ProjectBackground, type ProjectSurvey, type ProposalPoint } from "../../lib/project";
import { activities as defaultActivities } from "../../lib/content";
import { fallbackMeasures, type ProposalMeasure } from "../../lib/measures";
import "./admin.css";
import "./status.css";

type ActivityRow = { id?: string; slug: string; date_label: string; title: string; audience: string; location: string; participants_label: string; detail: string; cover_url: string; status: string };
type ContentRow = { id?: string; kind: "media" | "document" | "proposal"; title: string; summary: string; cover_url: string; source_url: string; status: string };
type StoredSession = { access_token: string; refresh_token?: string; expires_at?: number };
const SESSION_KEY = "fair-electricity-admin-session";
const emptyActivity = (): ActivityRow => ({ slug: "กิจกรรมใหม่", date_label: "", title: "", audience: "", location: "", participants_label: "", detail: "", cover_url: "", status: "draft" });
const emptyContent = (kind: ContentRow["kind"]): ContentRow => ({ kind, title: "", summary: "", cover_url: "", source_url: "", status: "draft" });
const defaultMedia: ContentRow[] = [
  { kind: "media", title: "ค่าไฟไทย ความเหลื่อมล้ำกับคำถามว่าทำไมยิ่งจนยิ่งจ่ายแพงกว่า?", summary: "KEY MESSAGES #262", source_url: "https://youtu.be/tgqFaZpFk94", cover_url: "/media/evidence-4.jpg", status: "published" },
  { kind: "media", title: "สิทธิผู้ใช้ไฟในแผน PDP สู่ไฟฟ้าราคาที่เป็นธรรม", summary: "FB กสม.", source_url: "https://www.facebook.com/reel/5439998426225570", cover_url: "/media/evidence-6.jpg", status: "published" },
  { kind: "media", title: "โซลาร์เซลล์เปลี่ยนค่าไฟให้เป็นธรรมทันทีได้อย่างไร", summary: "Quick Win", source_url: "https://www.facebook.com/reel/4292381747683320", cover_url: "/media/evidence-7.jpg", status: "published" },
  { kind: "media", title: "หน่วยไฟฟรีผ่านบัตรสวัสดิการแห่งรัฐ เข้าถึงไม่ง่าย", summary: "ประเด็นที่ต้องมองเห็น", source_url: "https://www.facebook.com/share/p/187Chps2q2/", cover_url: "/media/evidence-1.jpg", status: "published" },
  { kind: "media", title: "ค่าไฟเฉลี่ยต่อเดือนของครัวเรือนแตกต่างตามภูมิภาค", summary: "ข้อมูลเพื่อความเข้าใจ", source_url: "https://www.facebook.com/share/p/19ps8ytdtg/", cover_url: "/media/evidence-2.jpg", status: "published" },
  { kind: "media", title: "ไฟฟ้าไม่ใช่แค่ต้นทุนพลังงาน แต่คือสิทธิมนุษยชน", summary: "DataHatch", source_url: "https://youtu.be/tgqFaZpFk94", cover_url: "/media/evidence-9.jpg", status: "published" },
  { kind: "document", title: "สรุปข้อเสนอแนะค่าไฟฟ้าของ กสม.", summary: "เอกสารนำเสนอ", source_url: "/docs/เอกสารนำเสนอ-ข้อเสนอแนะค่าไฟ.pdf", cover_url: "", status: "published" },
  { kind: "document", title: "รายงานข้อเสนอแนะค่าไฟที่เป็นธรรม", summary: "รายงานโครงการ", source_url: "/docs/รายงานข้อเสนอแนะ-ฉบับกรกฎาคม.pdf", cover_url: "/media/report-cover.jpg", status: "published" },
  { kind: "document", title: "รายงานผลการดำเนินการและรายงานค่าใช้จ่าย", summary: "รายงานผลการดำเนินงาน", source_url: "/docs/รายงานผลการดำเนินการและรายงานค่าใช้จ่าย.docx", cover_url: "/media/report-cover.jpg", status: "published" },
  { kind: "document", title: "เวที กทม. ภาคกลาง ตะวันออก และตะวันตก", summary: "เอกสารนำเสนอรายภูมิภาค", source_url: "/docs/เอกสารนำเสนอ-กทม-กลาง-ตะวันออก-ตะวันตก.pdf", cover_url: "/media/evidence-8.jpg", status: "published" },
  { kind: "document", title: "เวทีรับฟังความคิดเห็นภาคเหนือ", summary: "เอกสารนำเสนอรายภูมิภาค", source_url: "/docs/เอกสารนำเสนอ-ภาคเหนือ.pdf", cover_url: "/media/evidence-10.jpg", status: "published" },
  { kind: "document", title: "เวทีรับฟังความคิดเห็นภาคใต้", summary: "เอกสารนำเสนอรายภูมิภาค", source_url: "/docs/เอกสารนำเสนอ-ภาคใต้.pdf", cover_url: "/media/evidence-11.jpg", status: "published" },
];
const defaultRights: ContentRow[] = [
  ["สิทธิในมาตรฐานการดำรงชีวิตที่เพียงพอ", "ทุกคนควรเข้าถึงไฟฟ้าที่จำเป็นต่อการดำรงชีวิตได้ ในราคาที่ไม่กระทบสิทธิขั้นพื้นฐานอื่น"],
  ["สิทธิในการมีส่วนร่วมของประชาชน", "ประชาชนมีสิทธิได้รับข้อมูลที่เข้าใจง่าย แสดงความคิดเห็น และมีส่วนร่วมอย่างมีความหมาย"],
  ["สิทธิในการเข้าถึงและใช้ประโยชน์จากทรัพยากรธรรมชาติ", "การจัดการทรัพยากรพลังงานต้องคำนึงถึงประโยชน์ของประชาชนและชุมชน"],
  ["สิทธิในการมีส่วนร่วมในการพัฒนาและได้รับประโยชน์อย่างเป็นธรรม", "การพัฒนาระบบไฟฟ้าต้องกระจายประโยชน์กลับสู่ประชาชนอย่างเป็นธรรม"],
  ["สิทธิในสิ่งแวดล้อมที่ดี", "ประชาชนควรได้รับการคุ้มครองจากผลกระทบทางสิ่งแวดล้อมที่เกิดจากพลังงาน"],
  ["สิทธิในการเข้าถึงสาธารณูปโภคขั้นพื้นฐานที่มีคุณภาพ", "รัฐมีหน้าที่จัดให้มีไฟฟ้าที่ทั่วถึง มั่นคง มีคุณภาพ และมีอัตราค่าบริการที่เป็นธรรม"],
].map(([title, summary]) => ({ kind: "proposal", title, summary, cover_url: "", source_url: "", status: "published" }));

export default function AdminPage() {
  const [active, setActive] = useState("ความเป็นมา");
  const [connection, setConnection] = useState("กำลังตรวจสอบการเชื่อมต่อ…");
  const [connectionTone, setConnectionTone] = useState("checking");
  const [background, setBackground] = useState<ProjectBackground>(fallbackBackground);
  const [committee, setCommittee] = useState<CommitteeMember[]>(fallbackCommittee);
  const [survey, setSurvey] = useState<ProjectSurvey>(fallbackSurvey);
  const [proposalPoints, setProposalPoints] = useState<ProposalPoint[]>(fallbackProposalPoints);
  const [measures, setMeasures] = useState<ProposalMeasure[]>(fallbackMeasures);
  const [activities, setActivities] = useState<ActivityRow[]>([]);
  const [content, setContent] = useState<ContentRow[]>([]);
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [token, setToken] = useState("");
  const [sessionReady, setSessionReady] = useState(false);
  const [message, setMessage] = useState("");

  const config = () => ({ url: process.env.NEXT_PUBLIC_SUPABASE_URL, key: process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY });
  const headers = () => { const { key } = config(); return { apikey: key ?? "", Authorization: `Bearer ${token || key || ""}` }; };
  const api = useCallback(async (path: string, init?: RequestInit) => { const { url } = config(); return fetch(`${url}/rest/v1/${path}`, { ...init, headers: { ...headers(), "Content-Type": "application/json", ...(init?.headers ?? {}) } }); }, [token]);

  const reload = useCallback(async () => {
    const { url, key } = config(); if (!url || !key) return;
    const get = async (path: string) => { const response = await fetch(`${url}/rest/v1/${path}`, { headers: { apikey: key, Authorization: `Bearer ${token || key}` } }); return response.ok ? response.json() : []; };
    const [backgroundRows, committeeRows, surveyRows, proposalRows, measureRows, activityRows, contentRows] = await Promise.all([
      get("project_background?id=eq.main&select=title,facts,closing"),
      get("committee_members?select=id,name,role,note,image_url,status,sort_order&order=sort_order.asc"),
      get("project_survey?id=eq.main&select=title,intro,highlights,source_url"),
      get("proposal_points?select=id,title,summary,sort_order,status&order=sort_order.asc"),
      get("proposal_measures?select=id,point_order,category_title,item_no,title,agencies,timeframe,detail,sort_order,status&order=sort_order.asc"),
      get("activities?select=id,slug,date_label,title,audience,location,participants_label,detail,cover_url,status&order=date_label.asc"),
      get("content_items?select=id,kind,title,summary,cover_url,source_url,status&order=created_at.desc"),
    ]);
    if (backgroundRows[0]) setBackground(backgroundRows[0]); if (committeeRows.length) setCommittee(committeeRows);
    if (surveyRows[0]) setSurvey({ ...fallbackSurvey, ...surveyRows[0], highlights: Array.isArray(surveyRows[0].highlights) && surveyRows[0].highlights.length ? surveyRows[0].highlights : fallbackSurvey.highlights });
    if (proposalRows.length) setProposalPoints(proposalRows); if (measureRows.length) setMeasures(measureRows); setActivities(activityRows); setContent(contentRows);
  }, [token]);

  useEffect(() => {
    const { url, key } = config();
    if (!url || !key) { setConnection("ยังไม่ได้ตั้งค่า Supabase"); setConnectionTone("warning"); return; }
    fetch(`${url}/rest/v1/content_items?select=id&limit=1`, { headers: { apikey: key, Authorization: `Bearer ${key}` } }).then((r) => { if (r.ok) { setConnection("เชื่อมต่อแล้ว"); setConnectionTone("success"); } else { setConnection("เชื่อมต่อไม่ได้ กรุณาตรวจ URL และ publishable key"); setConnectionTone("error"); } }).catch(() => { setConnection("เชื่อมต่อไม่ได้ กรุณาตรวจ URL และ publishable key"); setConnectionTone("error"); });
    const stored = window.localStorage.getItem(SESSION_KEY);
    if (!stored) { setSessionReady(true); return; }
    const restore = async () => {
      try {
        const saved = JSON.parse(stored) as StoredSession;
        let next = saved;
        if (saved.refresh_token && saved.expires_at && saved.expires_at * 1000 < Date.now() + 60_000) {
          const response = await fetch(`${url}/auth/v1/token?grant_type=refresh_token`, { method: "POST", headers: { apikey: key, "Content-Type": "application/json" }, body: JSON.stringify({ refresh_token: saved.refresh_token }) });
          if (response.ok) {
            const data = await response.json();
            next = { access_token: data.access_token, refresh_token: data.refresh_token, expires_at: data.expires_at };
            window.localStorage.setItem(SESSION_KEY, JSON.stringify(next));
          }
        }
        if (next.access_token) setToken(next.access_token); else window.localStorage.removeItem(SESSION_KEY);
      } catch { window.localStorage.removeItem(SESSION_KEY); }
      setSessionReady(true);
    };
    void restore();
  }, [reload]);

  async function login() { const { url, key } = config(); if (!url || !key) return; const response = await fetch(`${url}/auth/v1/token?grant_type=password`, { method: "POST", headers: { apikey: key, "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); const data = await response.json(); if (!response.ok) { setMessage(data.error_description || "เข้าสู่ระบบไม่สำเร็จ"); return; } const stored: StoredSession = { access_token: data.access_token, refresh_token: data.refresh_token, expires_at: data.expires_at }; window.localStorage.setItem(SESSION_KEY, JSON.stringify(stored)); setToken(data.access_token); setPassword(""); setMessage("เข้าสู่ระบบแล้ว เซสชันจะถูกจดจำในเครื่องนี้"); }
  function logout() { window.localStorage.removeItem(SESSION_KEY); setToken(""); setMessage("ออกจากระบบแล้ว"); }
  async function write(path: string, method: string, body: unknown, success: string) { if (!token) { setMessage("กรุณาเข้าสู่ระบบผู้ดูแลก่อนบันทึกข้อมูล"); return false; } const response = await api(path, { method, headers: { Prefer: "return=minimal" }, body: JSON.stringify(body) }); setMessage(response.ok ? success : "บันทึกไม่สำเร็จ ตรวจสิทธิ์ผู้ดูแลและ RLS ใน Supabase"); if (response.ok) await reload(); return response.ok; }
  async function remove(path: string, success: string) { if (!token) { setMessage("กรุณาเข้าสู่ระบบผู้ดูแลก่อนลบข้อมูล"); return; } if (!window.confirm("ยืนยันการลบรายการนี้?")) return; const response = await api(path, { method: "DELETE" }); setMessage(response.ok ? success : "ลบไม่สำเร็จ ตรวจสิทธิ์ผู้ดูแลและ RLS ใน Supabase"); if (response.ok) await reload(); }
  const saveBackground = () => write("project_background?on_conflict=id", "POST", { id: "main", ...background, status: "published" }, "บันทึกความเป็นมาแล้ว");
  const saveSurvey = () => write("project_survey?on_conflict=id", "POST", { id: "main", ...survey, status: "published" }, "บันทึกผลสำรวจแล้ว");
  async function saveProposalPoint(item: ProposalPoint, index: number) { if (!item.title) { setMessage("กรุณากรอกหัวข้อสาระสำคัญ"); return; } await write(item.id ? `proposal_points?id=eq.${item.id}` : "proposal_points", item.id ? "PATCH" : "POST", { title: item.title, summary: item.summary, sort_order: index, status: item.status || "published" }, "บันทึกสาระสำคัญแล้ว"); }
  async function saveMeasure(item: ProposalMeasure, index: number) { if (!item.title) { setMessage("กรุณากรอกชื่อมาตรการ"); return; } await write(item.id ? `proposal_measures?id=eq.${item.id}` : "proposal_measures", item.id ? "PATCH" : "POST", { ...item, sort_order: index, status: item.status || "published" }, "บันทึกมาตรการแล้ว"); }
  async function saveMember(member: CommitteeMember) { const body = { name: member.name, role: member.role, note: member.note ?? "", image_url: member.image_url ?? "", status: "published", sort_order: committee.indexOf(member) }; await write(member.id ? `committee_members?id=eq.${member.id}` : "committee_members", member.id ? "PATCH" : "POST", body, "บันทึกข้อมูลอนุกรรมการแล้ว"); }
  async function saveActivity(item: ActivityRow) { if (!item.slug || !item.title) { setMessage("กรุณากรอก slug และชื่อกิจกรรม"); return; } await write(item.id ? `activities?id=eq.${item.id}` : "activities", item.id ? "PATCH" : "POST", { ...item, status: item.status || "draft" }, "บันทึกกิจกรรมแล้ว"); }
  async function saveContent(item: ContentRow) { if (!item.title) { setMessage("กรุณากรอกชื่อรายการ"); return; } await write(item.id ? `content_items?id=eq.${item.id}` : "content_items", item.id ? "PATCH" : "POST", item, "บันทึกรายการคลังสื่อแล้ว"); }
  async function uploadFile(file: File, onUploaded: (url: string) => void) {
    if (!token) { setMessage("กรุณาเข้าสู่ระบบผู้ดูแลก่อนอัปโหลดไฟล์"); return; }
    const { url, key } = config(); if (!url || !key) return;
    const safeName = file.name.normalize("NFKD").replace(/[^a-zA-Z0-9._-]+/g, "-"); const path = `${Date.now()}-${safeName}`;
    const response = await fetch(`${url}/storage/v1/object/site-media/${path}`, { method: "POST", headers: { apikey: key, Authorization: `Bearer ${token}`, "Content-Type": file.type || "application/octet-stream", "x-upsert": "true" }, body: file });
    if (!response.ok) { setMessage("อัปโหลดไม่สำเร็จ กรุณาสร้าง bucket site-media และตั้งค่า Storage policy ก่อน"); return; }
    onUploaded(`${url}/storage/v1/object/public/site-media/${path}`); setMessage(`อัปโหลด ${file.name} แล้ว กดบันทึกเพื่อเก็บ URL`);
  }
  async function seedWebsiteContent() {
    if (!token) { setMessage("กรุณาเข้าสู่ระบบผู้ดูแลก่อนนำเข้าข้อมูล"); return; }
    if (!window.confirm("นำเข้าข้อมูลกิจกรรม สื่อ เอกสาร และสิทธิที่มีอยู่บนเว็บไซต์เข้าสู่ฐานข้อมูล?")) return;
    const activityBody = defaultActivities.map((item) => ({ slug: item.slug, date_label: item.date, title: item.title, audience: item.audience, location: item.location, participants_label: item.participants, detail: item.detail, cover_url: item.image, status: "published" }));
    const response = await api("activities?on_conflict=slug", { method: "POST", headers: { Prefer: "resolution=merge-duplicates,return=minimal" }, body: JSON.stringify(activityBody) });
    if (!response.ok) { setMessage("นำเข้ากิจกรรมไม่สำเร็จ กรุณาตรวจว่ามีตาราง activities แล้ว"); return; }
    const contentResponse = await api("content_items", { method: "POST", headers: { Prefer: "return=minimal" }, body: JSON.stringify([...defaultMedia, ...defaultRights]) });
    const pointsResponse = await api("proposal_points", { method: "POST", headers: { Prefer: "return=minimal" }, body: JSON.stringify(fallbackProposalPoints.map((item, index) => ({ title: item.title, summary: item.summary, sort_order: index, status: "published" }))) });
    const measuresResponse = await api("proposal_measures", { method: "POST", headers: { Prefer: "return=minimal" }, body: JSON.stringify(fallbackMeasures) });
    setMessage(contentResponse.ok && pointsResponse.ok && measuresResponse.ok ? "นำเข้าข้อมูลหน้าเว็บเข้าสู่หลังบ้านแล้ว" : "นำเข้ากิจกรรมแล้ว แต่บางหมวดอาจยังไม่เข้า กรุณาตรวจตารางฐานข้อมูล"); await reload();
  }
  const updateMember = (index: number, patch: Partial<CommitteeMember>) => setCommittee((rows) => rows.map((row, i) => i === index ? { ...row, ...patch } : row));
  const updateActivity = (index: number, patch: Partial<ActivityRow>) => setActivities((rows) => rows.map((row, i) => i === index ? { ...row, ...patch } : row));
  const updateContent = (index: number, patch: Partial<ContentRow>) => setContent((rows) => rows.map((row, i) => i === index ? { ...row, ...patch } : row));
  const field = (value: string, onChange: (value: string) => void, placeholder: string, area = false) => area ? <textarea className="admin-wide-input" rows={3} value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} /> : <input className="admin-wide-input" value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} />;

  function BackgroundPanel() { return <section className="admin-panel"><div className="panel-heading"><div><h2>ความเป็นมาของโครงการ</h2><p>เพิ่ม แก้ไข หรือลบแต่ละย่อหน้าได้</p></div><button className="primary-button" onClick={() => saveBackground()}>บันทึก</button></div>{field(background.title, (title) => setBackground({ ...background, title }), "หัวข้อ")}{background.facts.map((fact, index) => <div className="admin-repeat-row" key={index}>{field(fact, (value) => setBackground({ ...background, facts: background.facts.map((item, i) => i === index ? value : item) }), `เนื้อหาย่อหน้า ${index + 1}`, true)}<button className="danger-button" onClick={() => setBackground({ ...background, facts: background.facts.filter((_, i) => i !== index) })}>ลบ</button></div>)}<button className="outline-button" onClick={() => setBackground({ ...background, facts: [...background.facts, ""] })}>+ เพิ่มย่อหน้า</button>{field(background.closing, (closing) => setBackground({ ...background, closing }), "ข้อความสรุป", true)}</section>; }
  function CommitteePanel() { return <section className="admin-panel"><div className="panel-heading"><div><h2>คณะอนุกรรมการ</h2><p>จัดการชื่อ ตำแหน่ง รูปภาพ และสถานะการเผยแพร่</p></div><button className="outline-button" onClick={() => setCommittee([...committee, { name: "", role: "อนุกรรมการ", note: "", image_url: "" }])}>+ เพิ่มบุคคล</button></div>{committee.map((member, index) => <div className="admin-record" key={member.id ?? `new-${index}`}>{field(member.name, (value) => updateMember(index, { name: value }), "ชื่อ-นามสกุล")}{field(member.role, (value) => updateMember(index, { role: value }), "ตำแหน่ง")}{field(member.image_url ?? "", (value) => updateMember(index, { image_url: value }), "URL รูปภาพ") }<UploadInput label="อัปโหลดภาพอนุกรรมการ" accept="image/*" onUploaded={(url) => updateMember(index, { image_url: url })} />{field(member.note ?? "", (value) => updateMember(index, { note: value }), "หมายเหตุ") }<div className="record-actions"><button className="primary-button" onClick={() => saveMember(member)}>บันทึก</button>{member.id && <button className="danger-button" onClick={() => remove(`committee_members?id=eq.${member.id}`, "ลบอนุกรรมการแล้ว")}>ลบ</button>}</div></div>)}</section>; }
  function SurveyPanel() { return <section className="admin-panel"><div className="panel-heading"><div><h2>ผลสำรวจสาธารณะ</h2><p>แก้ไขบทนำ ประเด็นสำคัญ และลิงก์รายงานฉบับเต็ม</p></div><button className="primary-button" onClick={() => saveSurvey()}>บันทึก</button></div>{field(survey.title, (title) => setSurvey({ ...survey, title }), "หัวข้อ")}{field(survey.intro, (intro) => setSurvey({ ...survey, intro }), "คำโปรย", true)}{survey.highlights.map((item, index) => <div className="admin-repeat-row" key={index}>{field(item, (value) => setSurvey({ ...survey, highlights: survey.highlights.map((row, i) => i === index ? value : row) }), `ข้อค้นพบ ${index + 1}`, true)}<button className="danger-button" onClick={() => setSurvey({ ...survey, highlights: survey.highlights.filter((_, i) => i !== index) })}>ลบ</button></div>)}<button className="outline-button" onClick={() => setSurvey({ ...survey, highlights: [...survey.highlights, ""] })}>+ เพิ่มข้อค้นพบ</button>{field(survey.source_url, (source_url) => setSurvey({ ...survey, source_url }), "ลิงก์รายงานฉบับเต็ม") }<UploadInput label="อัปโหลดรายงานผลสำรวจ PDF" accept=".pdf,application/pdf" onUploaded={(url) => setSurvey({ ...survey, source_url: url })} /></section>; }
  function ProposalPointsPanel() { return <section className="admin-panel"><div className="panel-heading"><div><h2>สาระสำคัญของข้อเสนอแนะ</h2><p>แก้ไข เพิ่ม ลบ และจัดลำดับประเด็นสำคัญ 4 ข้อที่แสดงบนหน้าเว็บไซต์</p></div><button className="outline-button" onClick={() => setProposalPoints([...proposalPoints, { title: "", summary: "", status: "published" }])}>+ เพิ่มประเด็น</button></div>{proposalPoints.map((item, index) => <div className="admin-record" key={item.id ?? `proposal-point-${index}`}>{field(item.title, (value) => setProposalPoints(proposalPoints.map((row, i) => i === index ? { ...row, title: value } : row)), "หัวข้อประเด็น")}{field(item.summary, (value) => setProposalPoints(proposalPoints.map((row, i) => i === index ? { ...row, summary: value } : row)), "รายละเอียดข้อเสนอแนะ", true)}<select className="admin-wide-input" value={item.status ?? "published"} onChange={(e) => setProposalPoints(proposalPoints.map((row, i) => i === index ? { ...row, status: e.target.value } : row))}><option value="draft">ฉบับร่าง</option><option value="published">เผยแพร่</option><option value="archived">เก็บถาวร</option></select><div className="record-actions"><button className="primary-button" onClick={() => saveProposalPoint(item, index)}>บันทึก</button>{item.id && <button className="danger-button" onClick={() => remove(`proposal_points?id=eq.${item.id}`, "ลบประเด็นแล้ว")}>ลบ</button>}</div></div>)}</section>; }
  function MeasuresPanel() { return <section className="admin-panel"><div className="panel-heading"><div><h2>มาตรการเชิงข้อเสนอแนะ</h2><p>แก้ไข เพิ่ม ลบ และกำหนดหน่วยงานกับระยะเวลาของมาตรการแต่ละข้อ</p></div><button className="outline-button" onClick={() => setMeasures([...measures, { point_order: 1, category_title: "", item_no: 0, title: "", agencies: "", timeframe: "ระยะสั้น", detail: "", status: "published" }])}>+ เพิ่มมาตรการ</button></div>{measures.map((item, index) => <div className="admin-record measure-admin-record" key={item.id ?? `measure-${index}`}><div className="admin-form-grid">{field(String(item.point_order), (value) => setMeasures(measures.map((row, i) => i === index ? { ...row, point_order: Number(value) || 1 } : row)), "อยู่ในประเด็นที่ (1-4)")}{field(String(item.item_no), (value) => setMeasures(measures.map((row, i) => i === index ? { ...row, item_no: Number(value) || 0 } : row)), "ลำดับมาตรการ")}</div>{field(item.category_title, (value) => setMeasures(measures.map((row, i) => i === index ? { ...row, category_title: value } : row)), "ชื่อหมวด")}{field(item.title, (value) => setMeasures(measures.map((row, i) => i === index ? { ...row, title: value } : row)), "ชื่อมาตรการ")}{field(item.agencies, (value) => setMeasures(measures.map((row, i) => i === index ? { ...row, agencies: value } : row)), "เสนอถึงหน่วยงานใด")}{field(item.detail, (value) => setMeasures(measures.map((row, i) => i === index ? { ...row, detail: value } : row)), "รายละเอียดข้อเสนอแนะเชิงมาตรการ", true)}<select className="admin-wide-input" value={item.timeframe} onChange={(e) => setMeasures(measures.map((row, i) => i === index ? { ...row, timeframe: e.target.value as ProposalMeasure["timeframe"] } : row))}><option value="ระยะสั้น">ระยะสั้น</option><option value="ระยะกลาง">ระยะกลาง</option><option value="ระยะยาว">ระยะยาว</option></select><select className="admin-wide-input" value={item.status ?? "published"} onChange={(e) => setMeasures(measures.map((row, i) => i === index ? { ...row, status: e.target.value } : row))}><option value="draft">ฉบับร่าง</option><option value="published">เผยแพร่</option><option value="archived">เก็บถาวร</option></select><div className="record-actions"><button className="primary-button" onClick={() => saveMeasure(item, index)}>บันทึก</button>{item.id && <button className="danger-button" onClick={() => remove(`proposal_measures?id=eq.${item.id}`, "ลบมาตรการแล้ว")}>ลบ</button>}</div></div>)}</section>; }
  function ActivityPanel() { return <section className="admin-panel"><div className="panel-heading"><div><h2>กิจกรรม</h2><p>เพิ่ม แก้ไข ลบ และเปลี่ยนสถานะกิจกรรมที่แสดงในหน้าเว็บ</p></div><button className="outline-button" onClick={() => setActivities([...activities, emptyActivity()])}>+ เพิ่มกิจกรรม</button></div>{activities.length === 0 && <p className="admin-empty">ยังไม่มีกิจกรรมในฐานข้อมูล กด “เพิ่มกิจกรรม” เพื่อเริ่มต้น</p>}{activities.map((item, index) => <div className="admin-record" key={item.id ?? `new-activity-${index}`}>{field(item.title, (value) => updateActivity(index, { title: value }), "ชื่อกิจกรรม")}{field(item.slug, (value) => updateActivity(index, { slug: value }), "slug เช่น public-release")}<div className="admin-form-grid">{field(item.date_label, (value) => updateActivity(index, { date_label: value }), "วันที่")}{field(item.location, (value) => updateActivity(index, { location: value }), "สถานที่")}{field(item.audience, (value) => updateActivity(index, { audience: value }), "กลุ่มผู้เข้าร่วม")}{field(item.participants_label, (value) => updateActivity(index, { participants_label: value }), "จำนวนผู้เข้าร่วม")}</div>{field(item.detail, (value) => updateActivity(index, { detail: value }), "รายละเอียดกิจกรรม", true)}{field(item.cover_url, (value) => updateActivity(index, { cover_url: value }), "URL ภาพปก") }<select className="admin-wide-input" value={item.status} onChange={(e) => updateActivity(index, { status: e.target.value })}><option value="draft">ฉบับร่าง</option><option value="published">เผยแพร่</option><option value="archived">เก็บถาวร</option></select><div className="record-actions"><button className="primary-button" onClick={() => saveActivity(item)}>บันทึก</button>{item.id && <button className="danger-button" onClick={() => remove(`activities?id=eq.${item.id}`, "ลบกิจกรรมแล้ว")}>ลบ</button>}</div></div>)}</section>; }
  function UploadInput({ label, accept, onUploaded }: { label: string; accept: string; onUploaded: (url: string) => void }) { return <label className="upload-control"><span>{label}</span><input type="file" accept={accept} onChange={(e) => { const file = e.target.files?.[0]; if (file) uploadFile(file, onUploaded); e.currentTarget.value = ""; }} /></label>; }
  function ContentPanel({ kind, heading }: { kind: ContentRow["kind"]; heading: string }) { const rows = content.map((item, index) => ({ item, index })).filter(({ item }) => item.kind === kind); return <section className="admin-panel"><div className="panel-heading"><div><h2>{heading}</h2><p>{kind === "proposal" ? "ชื่อและคำอธิบายด้านล่างจะแสดงในการ์ดสิทธิและใน modal เมื่อคลิก" : "เพิ่ม แก้ไข ลบ URL ภาพปก เอกสาร และสถานะการเผยแพร่"}</p></div><button className="outline-button" onClick={() => setContent([...content, emptyContent(kind)])}>+ เพิ่มรายการ</button></div>{rows.length === 0 && <p className="admin-empty">ยังไม่มีรายการในหมวดนี้ กด “เพิ่มรายการ” เพื่อเริ่มต้น</p>}{rows.map(({ item, index }) => <div className="admin-record" key={item.id ?? `new-content-${index}`}>{field(item.title, (value) => updateContent(index, { title: value }), "ชื่อรายการ")}{field(item.summary, (value) => updateContent(index, { summary: value }), kind === "proposal" ? "รายละเอียดสำหรับ modal" : "คำอธิบาย", true)}{field(item.source_url, (value) => updateContent(index, { source_url: value }), "URL สื่อหรือเอกสาร")}{field(item.cover_url, (value) => updateContent(index, { cover_url: value }), "URL ภาพปก") }<div className="upload-row"><UploadInput label="อัปโหลดไฟล์ PDF / DOCX / วิดีโอ" accept=".pdf,.doc,.docx,video/*" onUploaded={(url) => updateContent(index, { source_url: url })} /><UploadInput label="อัปโหลดภาพปก" accept="image/*" onUploaded={(url) => updateContent(index, { cover_url: url })} /></div><select className="admin-wide-input" value={item.status} onChange={(e) => updateContent(index, { status: e.target.value })}><option value="draft">ฉบับร่าง</option><option value="published">เผยแพร่</option><option value="archived">เก็บถาวร</option></select><div className="record-actions"><button className="primary-button" onClick={() => saveContent(item)}>บันทึก</button>{item.id && <button className="danger-button" onClick={() => remove(`content_items?id=eq.${item.id}`, "ลบรายการแล้ว")}>ลบ</button>}</div></div>)}</section>; }

  const panels: Record<string, ReactNode> = { "ความเป็นมา": <BackgroundPanel />, "คณะอนุกรรมการ": <CommitteePanel />, "ผลสำรวจ": <SurveyPanel />, "กิจกรรม": <ActivityPanel />, "คลังสื่อ": <ContentPanel kind="media" heading="คลังสื่อ" />, "เอกสาร": <ContentPanel kind="document" heading="เอกสารเผยแพร่" />, "สาระสำคัญ": <ProposalPointsPanel />, "มาตรการ": <MeasuresPanel />, "ข้อเสนอแนะ": <ContentPanel kind="proposal" heading="ข้อเสนอแนะ" /> };
  const menu = Object.keys(panels);
  if (!sessionReady) return <main className="admin-shell"><section className="admin-content"><div className="admin-panel"><p className="admin-empty">กำลังตรวจสอบเซสชันผู้ดูแล…</p></div></section></main>;
  return <main className="admin-shell"><aside className="admin-sidebar"><div className="admin-brand"><span className="nhrc-mark">กสม.</span><span><b>ค่าไฟแฟร์</b><small>ระบบจัดการเนื้อหา</small></span></div><nav>{menu.map((label) => <button className={active === label ? "selected" : ""} onClick={() => setActive(label)} key={label}>{label}</button>)}</nav><div className="admin-status"><span className="status-dot"></span><span><b>{connection}</b><small>สถานะการเชื่อมต่อฐานข้อมูล</small></span></div></aside><section className="admin-content"><header className="admin-top"><div><p className="admin-kicker">CONTENT MANAGEMENT / {active.toUpperCase()}</p><h1>{active}</h1></div><div className="admin-actions"><button className="outline-button" onClick={seedWebsiteContent}>นำเข้าข้อมูลเดิม</button><a className="outline-button" href="/">ดูเว็บไซต์ ↗</a>{token && <button className="outline-button" onClick={logout}>ออกจากระบบ</button>}</div></header><div className={`admin-notice ${connectionTone}`}><span>i</span><p><b>{connection}</b><br />เพิ่ม แก้ไข ลบ อัปโหลดไฟล์ และเปลี่ยนสถานะเนื้อหาได้จากแต่ละหมวด</p></div>{!token && <section className="admin-panel"><div className="panel-heading"><div><h2>เข้าสู่ระบบผู้ดูแล</h2><p>เข้าสู่ระบบครั้งเดียว แล้วจัดการได้ทุกหมวด</p></div></div><div className="admin-form-row"><input value={email} onChange={(e) => setEmail(e.target.value)} placeholder="อีเมลผู้ดูแล" type="email" /><input value={password} onChange={(e) => setPassword(e.target.value)} placeholder="รหัสผ่าน" type="password" /><button className="primary-button" onClick={login}>เข้าสู่ระบบ</button></div>{message && <p className="admin-save-message">{message}</p>}</section>}{token && message && <p className="admin-save-message">{message}</p>}{token ? panels[active] : <section className="admin-panel"><p className="admin-empty">กรุณาเข้าสู่ระบบเพื่อจัดการเนื้อหาเว็บไซต์</p></section>}</section></main>;
}
